In [20]:
import pandas as pd
import numpy as np

#欠損値を取り除く
data = pd.Series([1,np.nan,3.5,np.nan,7])
#print(data)
#print(data.dropna())

#いくつ欠損値があるかによって取り除くかどうか決める
data = pd.DataFrame([[1.,6.5,3.],[1.,np.nan,np.nan],[np.nan,np.nan,np.nan],[np.nan,6.5,3.]])

#print("data\n",data)
#print("data.dropna()\n",data.dropna())
#print("data.dropna(how=all)\n",data.dropna(how="all"))

#列に対して行う場合
new_data = data.copy()
new_data[3] = np.nan
print("new_data\n",new_data)
#print("new_data.dropna(axis=columns, how=all)\n", new_data.dropna(axis="columns",how="all"))

#欠損値の数がある上限値未満のときだけ保持したい場合
print(new_data.dropna(thresh=1))

new_data
      0    1    2   3
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN
     0    1    2   3
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [ ]:
#欠損値の穴埋め
test_data = new_data.copy()

print(test_data)
print(test_data.fillna(0))
#列ごとに異なる値で埋める
print(test_data.fillna({0:0,1:100,2:200,3:300}))
#直前の値をそのまま入れる（limitでいくつ置き換えるか指定できる）
print(test_data.fillna(method="ffill",limit=1))

     0    1    2   3
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN
     0    1    2    3
0  1.0  6.5  3.0  0.0
1  1.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
3  0.0  6.5  3.0  0.0
     0      1      2      3
0  1.0    6.5    3.0  300.0
1  1.0  100.0  200.0  300.0
2  0.0  100.0  200.0  300.0
3  0.0    6.5    3.0  300.0
     0    1    2   3
0  1.0  6.5  3.0 NaN
1  1.0  6.5  3.0 NaN
2  1.0  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

C:\Users\kawor\AppData\Local\Temp\ipykernel_21024\3379391540.py:9: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print(test_data.fillna(method="ffill",limit=1))

In [32]:
#データの変形
#重複の除去
data = pd.DataFrame({"k1":["one", "two"] * 3 + ["two"], "k2":[1,1,2,3,3,4,4]})
print(data)

#重複かどうかを判定する
#print(data.duplicated())
#重複の場合消す
print(data.drop_duplicates())
#重複した値の最後のやつを残す
print(data.drop_duplicates(subset=["k1","k2"],keep="last"))
#指定した一部の列のみ
print(data.drop_duplicates(subset=["k1"]))

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4
    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
6  two   4
    k1  k2
0  one   1
1  two   1

In [35]:
#関数やマッピングを用いたデータ変換

data = pd.DataFrame({"food":["bacon","pulled pork", "bacon","pastrami","corned beef", "bacon","pastrami","honey ham","nova lox"],
                     "ounces":[4,3,12,6,7.5,8,3,5,6]})

#加工品に対してどの動物が使われたかマッピングする
meat_to_animal = {"bacon":"pig","pulled pork":"pig","pastrami":"cow","corned beef":"cow","honey ham":"pig","nova lox":"salmon"}

data["animal"] = data["food"].map(meat_to_animal)

data

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [41]:
#値の置き換え
#replaceを使うのがシンプルで柔軟性が高いらしい！
data = pd.Series([1.,-999.,2.,-999.,-1000.,3.])

#特定の値を欠損値に変える
#print(data.replace(-999,np.nan))
#複数の値の場合はこう！
#print(data.replace([-999,-1000], np.nan))
#値に対応する値の場合はこうでこう！
print(data.replace([-999,-1000],[np.nan,0]))
#これでも良い。というか、こっちのほうがわかりやすいし、引数として使えそう
print(data.replace({-999:np.nan,-1000:0}))
#これはどうだ！？
map_dict1 = {-999:np.nan,-1000:0}
print(data.replace(map_dict1))

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64
0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64
0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [47]:
#インデックスの名前を変える
data = pd.DataFrame({"food":["bacon","pulled pork", "bacon","pastrami","corned beef", "bacon","pastrami","honey ham","nova lox"],
                     "ounces":[4,3,12,6,7.5,8,3,5,6]})
data = data.rename(index={0:"a",1:"b",2:"c",3:"d",4:"e",5:"f",6:"g",7:"h"})

data

          food  ounces
a        bacon     4.0
b  pulled pork     3.0
c        bacon    12.0
d     pastrami     6.0
e  corned beef     7.5
f        bacon     8.0
g     pastrami     3.0
h    honey ham     5.0
8     nova lox     6.0

In [55]:
#離散化とビニング
ages = [20,22,25,27,21,23,37,31,61,45,41,32]
#このデータを18～25,26～35,36～60,61～の４つのビンに分割してみる。
bins = [18,25,35,60,100]
age_categories = pd.cut(ages,bins)
print(ages)
print(age_categories)
#pd.value_counts(age_categories)

#データの最小値・最大値をもとにビンを作って出す
data = np.random.uniform(size = 20)
pd.cut(data,4,precision=2)

[20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

[(0.12, 0.33], (0.12, 0.33], (0.33, 0.54], (0.33, 0.54], (0.33, 0.54], ..., (0.76, 0.97], (0.54, 0.76], (0.76, 0.97], (0.76, 0.97], (0.12, 0.33]]
Length: 20
Categories (4, interval[float64, right]): [(0.12, 0.33] < (0.33, 0.54] < (0.54, 0.76] < (0.76, 0.97]]

In [68]:
#外れ値の検出と除去
data = pd.DataFrame(np.random.standard_normal((1000,4)))
#print(data)
print(data.describe())#このメソッドなんか便利じゃね？
#4つの列のうち１つで外れ値を見つけたい。はずれ値としては絶対値が３より大きなものを考える。
cal = data[2]
#print(cal[cal.abs() > 3])
#3を上回るか-3を下回る値を1つ以上持つすべての行を選択する。
#print(data[(data.abs()>3).any(axis="columns")])

#これらの外れ値に対して、値を入れてみる。
#この書籍の悪いところは、値を入れるところで別の新しい項目が出てくるので混乱する。
data[data.abs()>3] = np.sign(data) * 10

print(data.describe())#このメソッドなんか便利じゃね？

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.004229    -0.073961     0.022070    -0.000313
std       1.020673     0.996264     1.003552     1.001547
min      -3.343670    -3.056535    -3.118804    -4.011884
25%      -0.684655    -0.752230    -0.689184    -0.685810
50%       0.040234    -0.067010     0.002042     0.014643
75%       0.694417     0.594698     0.727239     0.642819
max       3.430333     3.173058     2.853709     3.753179
                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.004142    -0.074077     0.008194    -0.000372
std       1.104085     1.083188     1.090395     1.237936
min     -10.000000   -10.000000   -10.000000   -10.000000
25%      -0.684655    -0.752230    -0.689184    -0.685810
50%       0.040234    -0.067010     0.002042     0.014643
75%       0.694417     0.594698     0.727239     0.642819
max      10.000000    10.000000     2.853709    10.000000

In [69]:
#順列（ランダムな並べ替え）やランダムサンプリング
#とりあえず、ランダムに順番を並べ替えるとかあることを知るだけ。

In [ ]:
#標識変数やダミー変数の計算
#ダミー変数は文字列を扱えないものが扱えるようにするためのもの

np.random.seed(12345)
values = np.random.uniform(size = 10)

values

bins = [0,0.2,0.4,0.6,0.8,1]

print(pd.get_dummies(pd.cut(values,bins)))
#あとあとまた使うらしいので、その時しっかり学ぼう。

   (0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0       False       False       False       False        True
1       False        True       False       False       False
2        True       False       False       False       False
3       False        True       False       False       False
4       False       False        True       False       False
5       False       False        True       False       False
6       False       False       False       False        True
7       False       False       False        True       False
8       False       False       False        True       False
9       False       False       False        True       False

In [73]:
#拡張データ型
#pandasの拡張データ型について
#基本的にはNUL許容のいろいろな型なのかな？

In [80]:
#文字列操作
#カンマ区切り文字列を分割するときはsplit
val = "a,b,   guido"
print(val.split(","))
#前後の空白を除去するのはstrip
val_test2 = [x.strip() for x in val.split(",")]
print(val_test2)
#連結するのは.join
print("::".join(val_test2))
#検索系は in（その中に存在するか） .index()（()の中の文字があれば1がくる？） .find()(indexと同じだが無い時は-1が返ってくる。)
print(val.index(","))
print(val.find("Z"))
#数を数えるのはcount
print(val.count(","))

['a', 'b', '   guido']
['a', 'b', 'guido']
a::b::guido
1
-1
2

In [ ]:
#正規表現
import re
text = "foo    bar\t baz   \tqux"

print(text)
text2 = re.split(r"\s+",text)

print(text2)
#コンパイルで定義しておくと楽ちんらしい。あとfindallはマッチした文字列を取り出す。
text2_comp = re.compile(r"\s+")
print(text2_comp.split(text))
print(text2_comp.findall(text))

#searchメソッドは最初にマッチした1つだけを返す。matchは文字列の先頭でマッチするかのみ。
text = "Dave dave@google.com Steve steve@steve@gmail.com Rob rob@gmail.com Ryan ryan@yahoo.com"
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"
regex = re.compile(pattern, flags=re.IGNORECASE)
print(regex.findall(text))
print(regex.search(text))
#subは文字列内にパターンが見つかった際にその部分を指定した別の文字列に置き換える。
print(regex.sub("REDACTED",text))

pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"
regex = re.compile(pattern, flags=re.IGNORECASE)
test_match = regex.match("wesm@bright.net")
print(test_match.groups())
#\1は1番目のグループにマッチしたやつ。\2は2番目のグループにマッチしたやつ
print(regex.sub(r"Username: \1, Domain: \2, Suffix: \3", text))
#文字列メソッドはたくさんあるから、こういう時はこう使うようにしっかりやる。
#正規表現は実務的に非常に使うので、型とかをマスターしておきたい。
#特に文字列系は必要になるだろう。

foo    bar	 baz   	qux
['foo', 'bar', 'baz', 'qux']
['foo', 'bar', 'baz', 'qux']
['    ', '\t ', '   \t']
['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']
<re.Match object; span=(5, 20), match='dave@google.com'>
Dave REDACTED Steve steve@REDACTED Rob REDACTED Ryan REDACTED
('wesm', 'bright', 'net')
Dave Username: dave, Domain: google, Suffix: com Steve steve@Username: steve, Domain: gmail, Suffix: com Rob Username: rob, Domain: gmail, Suffix: com Ryan Username: ryan, Domain: yahoo, Suffix: com

In [ ]:
#カテゴリ型データ
#処理速度やメモリ使用量が改善する！

values1 = pd.Series(["apple","orange","apple","apple"]*2)
#print(pd.unique(values1))
#print(pd.value_counts(values1))

#整数値の値テーブルを作っておいて、その後にディメジョンテーブルを使って、values1に戻す。
values2 = pd.Series([0,1,0,0]*2)
dim = pd.Series(["apple","orange"])

print(dim.take(values2))

#これを使えば、カテゴリ名を変更したり、すでにあるカテゴリの順序や位置を変えずに新たなカテゴリを追加できる。
#カテゴリ型にしたい場合は
cate = values1.astype("category")
#このカテゴリ型のカテゴリ情報を抽出する。
c = cate.array

#カテゴリ情報を取得するには。
print(c.categories)
print(c.codes)

#カテゴリを用いた計算
N = 10000000
labels = pd.Series(["foo","bar","baz", "qux"] * (N // 4))
categories = labels.astype("category")

print(labels.memory_usage(deep=True))
print(categories.memory_usage(deep=True))
#カテゴリ変数にするとGroupbyの演算は非常に高速にできる。

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object
Index(['apple', 'orange'], dtype='object')
[0 1 0 0 0 1 0 0]
600000132
10000544